-- Apr 10, 2013 10:32:53 PM VET
-- Order Prepay Schedule
CREATE TABLE CUST_OrderPrePaySchedule (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_Order_ID NUMERIC(10) NOT NULL, C_PaySchedule_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, CUST_OrderPrePaySchedule_ID NUMERIC(10) NOT NULL, DiscountAmt NUMERIC NOT NULL, DiscountDate TIMESTAMP NOT NULL, DueAmt NUMERIC NOT NULL, DueDate TIMESTAMP NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, IsValid CHAR(1) CHECK (IsValid IN ('Y','N')) NOT NULL, Processed CHAR(1) CHECK (Processed IN ('Y','N')) NOT NULL, Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT CUST_OrderPrePaySchedule_Key PRIMARY KEY (CUST_OrderPrePaySchedule_ID))
;

